# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9518c24325ba654cd028ef9bd0815664d3862467789145dc20cc5aff076eb40356bdb9fed7e9d6fab77f1211990f255f29aad7f1370b36849236740b45be604

test:
  secret_key_base: 3e46ab46d4624abddc7875b3c6776d6c74d0d41a7311e2e9041ce96eaf637d003b3429bfc43e348858f118d13f8e9459d448312d181987b75cba5ee25972d075

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
